default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TEACHER_APP_DATABASE_USER'] %>
  password: <%= ENV['TEACHER_APP_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: to_do_development

test:
  <<: *default
  database: to_do_test

production:
  <<: *default
  database: to_do_production
